set ERRLOG=C:\AutomationEnvironment\Logs\%DATE:/=-%@%TIME::=-%
set ERRLOG=%ERRLOG: =%
set ERRLOG=%ERRLOG:,=.%.txt
echo 'CMD Error Log'>%ERRLOG%


REM -20dB
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Babble-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

REM Dynamic Range
echo 'Testing Dynamic Range'>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_33.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 33 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 30 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_27.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 27 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_24.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 24 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_21.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 21 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_18.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 18 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 15 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_12.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 12 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_9.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 9 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_6.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 6 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_3.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 3 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20_0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-3.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -3 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-6.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -6 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-9.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -9 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-12.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -12 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -15 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-18.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -18 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-21.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -21 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-24.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -24 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-27.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -27 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-30.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -30 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-33.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -33 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Dynamic_Range_Car80-20-36.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -36 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

REM FA
echo 'Testing FA'>>%ERRLOG%
REM 2words
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AutomationEnvironment\jukebox\logs\list_FA_2words_Trigg_quite.txt C:\AutomationEnvironment\lists\list_FA_2words.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
REM Long Talks
"C:\AutomationEnvironment\WinAutomation_Executables\Run_Long_Files_With_Listener_CSV.exe" C:\\AutomationEnvironment\\lists\\FA_LongTalks_with_Times.csv "Time per wav in the list (csv)" Google 0

REM Noises -20dB
echo 'Testing Noises -20dB'>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_street-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Crossroads-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_5ms-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_4ms-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_3ms-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%


REM Noises 0dB
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Babble_0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_street-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Crossroads-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Crossroads-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_5ms-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_4ms-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_3ms-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

REM Noises 10dB
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Babble_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_street_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Crossroads_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_5ms_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_4ms_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_3ms_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

REM TESTING Car80 noise
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -10 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 25 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Car80_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 30 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

REM  BABBLE
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Babble-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Babble-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -10 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Babble-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Babble_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Babble_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Babble_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

REM Cafeteria
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -10 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 25 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 30 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

REM OFFICE
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -10 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_cafeteria_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 30 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 25 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Office_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 30 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%


REM STREET
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_street-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_street-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -10 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_street-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_street_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_street_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_street_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_street_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 25 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%


REM crossroads
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Crossroads-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Crossroads-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -10 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Crossroads-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_Crossroads_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

REM WINDS
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_5ms-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_5ms-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -10 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_5ms-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_5ms_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_5ms_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_4ms-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_4ms-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -10 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_4ms-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_4ms_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_4ms_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_4ms_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_4ms_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 25 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_3ms-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_3ms-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -10 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_3ms-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_3ms_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_3ms_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_3ms_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_3ms_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 25 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -10 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 5 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 15 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 20 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 25 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\Jukebox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_Hey_Jabra_2ms_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 30 4 1 LJ Trig Jabra Rubidium None "Hey Jabra" ""  "LJ- Trigger" 2>>%ERRLOG%

