Rem Setting up Error log
set ERRLOG=C:\AutomationEnvironment\Logs\%DATE:/=-%@%TIME::=-%
set ERRLOG=%ERRLOG: =%
set ERRLOG=%ERRLOG:,=.%.txt
echo 'CMD Error Log'>%ERRLOG%

REM REM Sanity
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80-20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Babble-20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80-0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Babble_0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM REM TESTING Car80 noise
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_25.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 25 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_30.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 30 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM REM FA
REM REM 2words
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AutomationEnvironment\logs\FA_2Words_8213_ASR_With_TRIG-HeyJabra.txt C:\AutomationEnvironment\lists\FA_2Words_8213_ASR_With_TRIG-HeyJabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM REM -20dB
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria-20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office-20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_street-20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Crossroads-20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_5ms-20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_4ms-20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_3ms-20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms-20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%


REM REM Noises 0dB
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria-0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office-0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_street-0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Crossroads-0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Crossroads-0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_5ms-0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_4ms-0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_3ms-0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms-0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 0 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM REM Noises 10dB
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Babble_10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria_10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office_10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_street_10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Crossroads_10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_5ms_10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_4ms_10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_3ms_10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms_10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM REM TESTING Car80 noise
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_25.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 25 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Car80_30.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 30 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM REM  BABBLE
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Babble-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Babble-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Babble-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Babble_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Babble_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Babble_20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM REM Cafeteria
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria_20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria_25.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 25 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria_30.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 30 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM REM OFFICE
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_cafeteria_30.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 30 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office_20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office_25.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 25 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Office_30.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 30 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%


REM REM STREET
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_street-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_street-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_street-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_street_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_street_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_street_20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_street_25.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 25 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%


REM REM crossroads
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Crossroads-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Crossroads-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Crossroads-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Crossroads_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM REM WINDS
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_5ms-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_5ms-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_5ms-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_5ms_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_5ms_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_4ms-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_4ms-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_4ms-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_4ms_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_4ms_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_4ms_20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_4ms_25.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 25 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_3ms-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_3ms-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_3ms-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_3ms_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_3ms_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_3ms_20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_3ms_25.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 25 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms-10.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -10 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms-5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms_5.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 5 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 15 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms_20.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 20 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms_25.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 25 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_2ms_30.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 30 6 2 EB TRIG/ASR Jabra_old Rubidium-Jabra None 2>>%ERRLOG%

REM Dynamic Range
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-54.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -54 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG% 
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-51.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -51 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-48.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -48 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-45.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -45 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-42.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -42 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-39.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -33 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-30.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -30 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-27.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -27 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-24.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -24 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-21.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -21 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM pYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_24.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 24 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_27.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 27 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_30.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 30 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_33.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 33 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_36.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 36 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_39.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 39 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%

PYTHON C:\AutomationEnvironment\Jukebox\JukeBox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -15 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None "6,8,10,12,14,16" "2" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\JukeBox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80_6.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 6 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None "6,8,10,12,14,16" "2" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\JukeBox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-12.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -12 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None "6,8,10,12,14,16" "2" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\JukeBox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_3.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 3 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None "6,8,10,12,14,16" "2" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\JukeBox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-9.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -9 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None "6,8,10,12,14,16" "2" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\JukeBox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-6.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -6 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None "6,8,10,12,14,16" "2" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\JukeBox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-3.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -3 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None "6,8,10,12,14,16" "2" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\JukeBox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-18.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -18 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None "6,8,10,12,14,16" "2" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\JukeBox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_0.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None "6,8,10,12,14,16" "2" 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\Jukebox\JukeBox_main.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80_9.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 9 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None "6,8,10,12,14,16" "2" 2>>%ERRLOG%

REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20-21.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -21 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_12.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 12 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_15.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 15 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_18.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 18 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_ASR_Fitness_without_resume_Hey-Jabra_Dynamic_Range_Car80-20_21.txt C:\AutomationEnvironment\lists\ASR_TRIG_FITNNESS_Without_Resume_Hey-Jabra.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 21 -20 9 0 EB TRIG/ASR Jabra_old Rubidium None 2>>%ERRLOG%

C:\AutomationEnvironment\BatchFiles\RUN_Hey-Jabra_Full_TEST_Trigger.bat