Rem Setting up Error log
set TIMESTAMP=%DATE:/=-%@%TIME::=-%
set TIMESTAMP=%TIMESTAMP: =%
set ERRLOG=%TIMESTAMP:,=.%.txt
set logpath=C:\AUTOMATIONENVIRONMENT\logs\
set ERRLOG=%logpath%%ERRLOG%
echo 'CMD Error Log'>%ERRLOG%
REM Setting up variables to be Re-used latter
set JukeBox20=C:\AutomationEnvironment\Jukebox\JukeBox_main.py
set JukeBox15=C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py
set testname=Trunk_Revision-3591_Standby_
REM set testname=CSR_Combined_A2DP_NOPre_NoPost_
REM set testname=grandson_28_9FT-distance_
set listpath=C:\AutomationEnvironment\lists\
set noisefilespath=C:\AutomationEnvironment\NoiseFiles\
set CarNoise=%noisefilespath%Headset_Car80_Noise.wav
set BabbleNoise=%noisefilespath%Babble-20kHz-2min-11dB.wav
set CafeteriaNoise=%noisefilespath%cafeteria_mono_150s.wav
set OfficeNoise=%noisefilespath%Headset_Office_Noise.wav
set StreetNoise=%noisefilespath%street_mono_193s.wav
set CrossroadsNoise=%noisefilespath%Crossroads.wav
set Winds_5msNoise=%noisefilespath%Wind_5ms.wav
set Winds_4msNoise=%noisefilespath%Wind_4ms.wav
set Winds_3msNoise=%noisefilespath%Wind_3ms.wav
set Winds_2msNoise=%noisefilespath%Wind_2ms.wav
set Microwave=%noisefilespath%Microwave_Sound_Effect_30_sec_White_Noise_16k16bMonoNorm49.wav
set Music=%noisefilespath%05_happy_(from_despicable_me_2)_16k16MonoNorm49.wav

REM Sanity
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_A2DP_Amazon_Trigger_Alexa_WhatsTheTime_Car80-20.txt C:\AutomationEnvironment\lists\Alexa_network_WhatsTheTime.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 8 0 EB TRIG Jabra_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Babble-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Car80-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Babble_0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%


REM Dynamic Range
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-54.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -54 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG% 
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-51.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -51 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-48.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -48 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-45.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -45 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-42.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -42 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-39.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -33 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-30.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -30 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-27.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -27 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-24.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -24 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-21.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -21 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
pYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_24.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 24 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_27.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 27 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 30 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_33.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 33 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_36.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 36 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_39.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 39 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-18.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -18 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -15 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-12.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -12 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-9.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -9 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-6.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -6 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20-3.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -3 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_3.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 3 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_6.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 6 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_9.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 9 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_12.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 12 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 15 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_18.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 18 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Dynamic_Range_Car80-20_21.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 21 -60 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%


REM -20dB
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_street-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Crossroads-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_5ms-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_4ms-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_3ms-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms-20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%


REM FA
REM 2words
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AutomationEnvironment\logs\list_FA_2words.txt C:\AutomationEnvironment\lists\list_FA_2words.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 8 0 EB  TRIG Jabra_old Rubidium None 2>>%ERRLOG%
REM REM Long Talks
PYTHON %JukeBox20% %logpath%%testname%LongTalks1_%TIMESTAMP%.txt %listpath%FA_LongTalks1_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 1200 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks2_%TIMESTAMP%.txt %listpath%FA_LongTalks2_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 8500 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks3_%TIMESTAMP%.txt %listpath%FA_LongTalks3_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 6500 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks4_%TIMESTAMP%.txt %listpath%FA_LongTalks4_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 6500 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks5_%TIMESTAMP%.txt %listpath%FA_LongTalks5_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 4450 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks6_%TIMESTAMP%.txt %listpath%FA_LongTalks6_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 1100 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks7_%TIMESTAMP%.txt %listpath%FA_LongTalks7_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 5500 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks8_%TIMESTAMP%.txt %listpath%FA_LongTalks8_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 6300 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks9_%TIMESTAMP%.txt %listpath%FA_LongTalks9_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 5500 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks10_%TIMESTAMP%.txt %listpath%FA_LongTalks10_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 2800 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks11_%TIMESTAMP%.txt %listpath%FA_LongTalks11_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 3500 2>>%ERRLOG%
PYTHON %JukeBox20% %logpath%%testname%LongTalks-Friends_%TIMESTAMP%.txt %listpath%FA_LongTalks12_Alexa.txt None 0 0 4 0 Listener TRIG Alexa Long_Talks_Standby None "" "" "" "" 1640 2>>%ERRLOG%


REM Amazon 24Hr FA
PYTHON %JukeBox20% %logpath%%testname%_FARTestRecording_24_hrs_16kHz_Norm49_0_%TIMESTAMP%.txt %listpath%24-Hours-FA_from_Amazon.txt None 0 0 6 0 EB TRIG Alexa Standby None "" "" "" "" 86700 2>>%ERRLOG%






REM Noises 0dB
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_street-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Crossroads-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Crossroads-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_5ms-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_4ms-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_3ms-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms-0.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 0 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%

REM Noises 10dB
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Car80_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Babble_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_street_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Crossroads_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_5ms_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_4ms_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_3ms_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms_10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%

REM TESTING Car80 noise
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Car80-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Car80-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Car80-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Car80_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Car80_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Car80_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Car80_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 25 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Car80_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 30 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%

REM  BABBLE
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Babble-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Babble-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Babble-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Babble_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Babble_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Babble_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%

REM Cafeteria
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 25 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 30 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%

REM OFFICE
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_cafeteria_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 30 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 25 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Office_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 30 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%


REM STREET
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_street-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_street-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_street-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_street_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_street_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_street_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_street_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 25 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%


REM crossroads
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Crossroads-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Crossroads-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Crossroads-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_Crossroads_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%

REM WINDS
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_5ms-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_5ms-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_5ms-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_5ms_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_5ms_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%

PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_4ms-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_4ms-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_4ms-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_4ms_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_4ms_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_4ms_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_4ms_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 25 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%

PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_3ms-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_3ms-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_3ms-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_3ms_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_3ms_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_3ms_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_3ms_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 25 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%

PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms-15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms-10.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -10 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms-5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms_5.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 5 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms_15.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 15 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms_20.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 20 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms_25.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 25 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_JayBird_Trigger_Hey-Jabra_2ms_30.txt C:\AutomationEnvironment\lists\hey_jabra_amazon_X4.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 30 9 0 EB TRIG Jabra_old Rubidium None 2>>%ERRLOG%

C:\AutomationEnvironment\BatchFiles\RUN_Hey-Jabra_Full_TEST_ASR.bat