Rem Setting up Error log
set ERRLOG=C:\AutomationEnvironment\Logs\%DATE:/=-%@%TIME::=-%
set ERRLOG=%ERRLOG: =%
set ERRLOG=%ERRLOG:,=.%.txt
echo 'CMD Error Log'>%ERRLOG%

REM Sanity
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Babble-20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80-20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 9 0 Listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80-0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Babble_0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%


REM Dynamic Range
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-54.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -54 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG% 
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-51.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -51 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-48.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -48 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-45.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -45 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-42.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -42 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-39.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -33 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-30.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -30 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-27.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -27 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-24.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -24 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-21.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -21 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_18.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 18 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_21.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 21 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM pYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_24.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 24 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_33.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 33 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_36.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 36 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_39.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 39 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -15 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_6.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 6 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-12.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -12 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_3.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 3 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-9.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -9 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-6.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -6 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-3.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -3 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 15 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_12.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 12 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20_9.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 9 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Dynamic_Range_Car80-20-18.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav -18 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

REM FA
REM 2words
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AutomationEnvironment\logs\CSR_Fitness_A2DP_Fixed-freeze_No-reset_FA_1000X2words_noisy.txt C:\AutomationEnvironment\lists\FA_2words_1000_Women.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AutomationEnvironment\logs\CSR_Fitness_A2DP_Fixed-freeze_No-reset_FA_1000X2words.txt C:\AutomationEnvironment\lists\FA_2words_1000_Women.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 4 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%




REM -20dB
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria-20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office-20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_street-20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Crossroads-20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_5ms-20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_4ms-20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_3ms-20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms-20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%


REM Noises 0dB
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria-0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office-0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_street-0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Crossroads-0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_5ms-0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_4ms-0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_3ms-0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms-0.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 0 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

REM Noises 10dB
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80_10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Babble_10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria_10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office_10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_street_10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Crossroads_10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_5ms_10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_4ms_10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_3ms_10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms_10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

REM TESTING Car80 noise
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80-10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80-5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80_5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80_15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80_20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80_25.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 25 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Car80_30.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 30 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%


REM FA
REM 2words
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AutomationEnvironment\logs\CSR_Fitness_A2DP_Fixed-freeze_No-reset_FA_2words.txt C:\AutomationEnvironment\lists\list_FA_2words_Google_verification.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
REM Long Talks
REM "C:\AutomationEnvironment\WinAutomation_Executables\Run_Long_Files_With_Listener_CSV.exe" C:\\AutomationEnvironment\\lists\\FA_LongTalks_with_Times.csv "Time per wav in the list (csv)" 0 Google listener Hey-Jabra None


REM  BABBLE
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Babble-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Babble-10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Babble-5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 -5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Babble_5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Babble_15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Babble_20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Babble-20kHz-2min-11dB.wav 0 20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

REM Cafeteria
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria-10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria-5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 -5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria_5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria_15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria_20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria_25.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 25 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria_30.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 30 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

REM OFFICE
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office-10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office-5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 -5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office_5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office_15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_cafeteria_30.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\cafeteria_mono_150s.wav 0 30 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office_20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office_25.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 25 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Office_30.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Office_Noise.wav 0 30 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%


REM STREET
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_street-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_street-10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_street-5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 -5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_street_5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_street_15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_street_20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_street_25.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\street_mono_193s.wav 0 25 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%


REM crossroads
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Crossroads-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Crossroads-10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Crossroads-5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 -5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_Crossroads_5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Crossroads.wav 0 5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

C:\AutomationEnvironment\BatchFiles\RUN_Hey-Jabra_Full_TEST_ASR.bat
REM "C:\AutomationEnvironment\WinAutomation_Executables\Run_Long_Files_With_Listener_CSV.exe" C:\\AutomationEnvironment\\lists\\FA_LongTalks_with_Times.csv "Time per wav in the list (csv)" 0 Google listener Hey-Jabra None


REM WINDS
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_5ms-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_5ms-10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_5ms-5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 -5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_5ms_5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_5ms_15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_5ms.wav 0 15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_4ms-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_4ms-10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_4ms-5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 -5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_4ms_5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_4ms_15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_4ms_20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_4ms_25.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_4ms.wav 0 25 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_3ms-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_3ms-10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_3ms-5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 -5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_3ms_5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_3ms_15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_3ms_20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_3ms_25.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_3ms.wav 0 25 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms-15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms-10.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -10 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms-5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 -5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms_5.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 5 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms_15.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 15 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms_20.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 20 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms_25.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 25 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%
PYTHON C:\AutomationEnvironment\JukeBox_V1\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\CSR_Fitness_A2DP_OK-Google_No-Reset_2ms_30.txt C:\AutomationEnvironment\lists\OK_Google_Dev_list285files.txt C:\AutomationEnvironment\NoiseFiles\Wind_2ms.wav 0 30 9 0 listener TRIG Google_old Rubidium Rubidium 2>>%ERRLOG%

C:\AutomationEnvironment\BatchFiles\RUN_Hey-Jabra_Full_TEST_ASR.bat