PYTHON C:\AutomationEnvironment\JukeBox\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\JukeBox_Jabra_Amazon_logs_New_X4_2sec.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 2 2 MP TRIG Jabra

PYTHON C:\AutomationEnvironment\JukeBox\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\JukeBox_Jabra_Amazon_logs_New_X4_5sec.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 5 2 MP TRIG Jabra

PYTHON C:\AutomationEnvironment\JukeBox\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\JukeBox_Jabra_Amazon_logs_New_X4_10sec.txt C:\AutomationEnvironment\lists\hey_jabra_amazonX4.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 10 2 MP TRIG Jabra

PYTHON C:\AutomationEnvironment\JukeBox\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\JukeBox_Jabra_47_logs_new_2.txt C:\AutomationEnvironment\lists\Hey_Jabra_47files.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 2 2 MP TRIG Jabra

PYTHON C:\AutomationEnvironment\JukeBox\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\JukeBox_Jabra_Amazon_logs_1min.txt C:\AutomationEnvironment\lists\hey_jabra_amazon.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 60 2 MP TRIG Jabra

PYTHON C:\AutomationEnvironment\JukeBox\JukeboxAuto.py C:\AUTOMATIONENVIRONMENT\logs\JukeBox_Jabra_Amazon_logs_5min.txt C:\AutomationEnvironment\lists\hey_jabra_amazon.txt C:\AutomationEnvironment\NoiseFiles\Headset_Car80_Noise.wav 0 -20 300 2 Listener TRIG Jabra